# Generated by Django 5.2.1 on 2025-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_category_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_before',
            field=models.IntegerField(choices=[(0, 'Tam zamanında'), (30, '30 dakika önce'), (60, '1 saat önce'), (90, '1.5 saat önce'), (120, '2 saat önce'), (180, '3 saat önce'), (240, '4 saat önce'), (360, '6 saat önce'), (720, '12 saat önce'), (1440, '24 saat önce')], default=30, verbose_name='Hatırlatıcı'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Hatırlatıcı Gönderildi'),
        ),
    ]
