# Generated by Django 5.2.1 on 2025-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_task_reminder_before_task_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_sent',
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_before',
            field=models.IntegerField(choices=[(5, '5 dakika önce'), (15, '15 dakika önce'), (30, '30 dakika önce'), (60, '1 saat önce'), (1440, '1 gün önce')], default=30, verbose_name='Hatırlatıcı'),
        ),
    ]
