# Generated by Django 5.2.1 on 2025-05-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_remove_task_reminder_sent_alter_task_reminder_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_before',
        ),
    ]
