# Generated by Django 5.2.1 on 2025-05-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_grouppost_file_grouppost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Sabitlendi mi?'),
        ),
    ]
