# Generated by Django 5.2.1 on 2025-05-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_grouppostreaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPostReaction',
        ),
    ]
