# Generated by Django 5.2.1 on 2025-05-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification_system', '0001_initial'),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task_manager.task', verbose_name='İlgili Görev'),
        ),
    ]
